# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pusher < Formula
  desc "Pusher CLI!"
  homepage "https://pusher.com/"
  version "0.20"

  on_macos do
    url "https://github.com/pusher/cli/releases/download/v0.20/pusher_0.20_Darwin_x86_64.tar.gz"
    sha256 "b159e18339c039c4de6a616b3f7c7adac939f2f1fb5d22c35def5b800675fb7b"

    def install
      bin.install "pusher"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Pusher
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pusher/cli/releases/download/v0.20/pusher_0.20_Linux_x86_64.tar.gz"
      sha256 "0cdcd593b9dbe2165a96766c0626df1123abb9ef30069a441988fc00326cdae4"

      def install
        bin.install "pusher"
      end
    end
  end
end
