# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pusher < Formula
  desc "Pusher CLI!"
  homepage "https://pusher.com/"
  version "0.15"

  on_macos do
    url "https://github.com/pusher/cli/releases/download/v0.15/pusher_0.15_Darwin_x86_64.tar.gz"
    sha256 "7892167af21ec1eda3323b93e4e139ff28b1de674a18428c413293085654aa38"

    def install
      bin.install "pusher"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Pusher
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pusher/cli/releases/download/v0.15/pusher_0.15_Linux_x86_64.tar.gz"
      sha256 "edfa7a64ba96d65c1cbc12251dfda8d7459e6112919bc81fe8f0c615260ecc1f"

      def install
        bin.install "pusher"
      end
    end
  end
end
