# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pusher < Formula
  desc "Pusher CLI!"
  homepage "https://pusher.com/"
  version "0.18"

  on_macos do
    url "https://github.com/pusher/cli/releases/download/v0.18/pusher_0.18_Darwin_x86_64.tar.gz"
    sha256 "0d23f0b1bc6315ec56977e50a8e322ad1c14218f0f41c407c54c80243b230175"

    def install
      bin.install "pusher"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Pusher
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pusher/cli/releases/download/v0.18/pusher_0.18_Linux_x86_64.tar.gz"
      sha256 "8f4edb60448666e6591dc1e1ea75e6594931b2477c0ba2de52ca939be221fd9b"

      def install
        bin.install "pusher"
      end
    end
  end
end
